[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs

lib_deps =
    bblanchon/ArduinoJson @ ^7.0.0
    vshymanskyy/TinyGSM @ ^0.11.7
    knolleary/PubSubClient @ ^2.8
    adafruit/Adafruit PN532 @ ^1.3.3
    # Dependências para TinyGSM
    vshymanskyy/StreamDebugger @ ^1.0.1
    # Dependências para WebServer
    me-no-dev/ESP Async WebServer @ ^1.2.3
    me-no-dev/AsyncTCP @ ^1.1.1
